Completely updated da bootstrap script
* Add exception handlers to different cases (will also add IPC_LOCK checks soon
but for now we'll warn the user first)
* Do database migrations on start unless skipped by user through setting SKIP_DB_MIGRATIONS_MANUAL to true
* ...and alot of chaos management included

Signed-off-by: Andrei Jiroh Eugenio Halili <andreijiroh@madebythepins.tk>

diff --git a/bootstrapper-handler b/bootstrapper-handler
--- a/bootstrapper-handler
+++ b/bootstrapper-handler
@@ -1,4 +1,5 @@
 #!/bin/bash
+# shellcheck disable=SC2034,SC2155,SC1004 shell=bash
 
 ##### LICENSE #####
 # MIT License
@@ -33,7 +34,7 @@ set -e
 # Note above that we run dumb-init as PID 1 in order to reap zombie processes
 # as well as forward signals to all processes in its session. Normally, sh
 # wouldn't do either of these functions so we'd leak zombies as well as do
-# unclean termination of all our sub-processes.
+# unclean termination of all our sub-processes. We don't know about bash.
 
 # Prevent core dumps
 ulimit -c 0
@@ -72,7 +73,7 @@ if [ -n "$VAULT_LOCAL_CONFIG" ]; then
     echo "$VAULT_LOCAL_CONFIG" > "$VAULT_CONFIG_DIR/local.json"
 fi
 
-### COPIED FROM https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh - START ###
+### COPIED FROM https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh - END ###
 
 useColor() {
   # Only use colors if connected to a terminal
@@ -122,23 +123,70 @@ extractEnvVars() {
      export DATABASE_URL="postgres://bullshithq:shitfuckery@db/hashcorpvault_db"
      export PGUSER=bullshithq PGPASSWORD=shitfuckery PGHOST=db PGPORT=5432 PGDATABASE=hashicorpvault_db
   elif [[ $DATABASE_URL == "" ]] && [[ $PGHOST != "" && $PGPORT != "" ]]; then
-     export DATABASE_URL="postgres://$PGUSER:$PGPASSWORD@$PGHOST:PGPORT/$PGDATABASE"
+     export DATABASE_URL="postgres://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE"
   fi
 
   if [[ $DISABLE_MEMORY_LOCKING == "" ]]; then
+     warn "Memory locking is enabled, make sure you add the IPC_LOCK cap when running this image or atleast your PaaS provider supports it."
+     warn "If Vault complains about this, stop and start with DISABLE_MEMORY_LOCKING variable set to true"
      export DISABLE_MEMORY_LOCKING=false
+  fi
+}
+
+runDBMigrations() {
+  echoStageName "Running database migrations in 15 seconds"
+  sleep 15
+  if [[ $SKIP_DB_MIGRATIONS_MANUAL == "true" ]]; then
+    warn "Postgres database migrations are being skipped, proceed at your own risk"
+  elif [[ $PGPORT == "" ]] && [[ $PGDATABASE == "" ]]; then
+    error "PGHOST and PGPORT are required for database migrations to run but found missing, aborting..."
+    exit 2
+  elif [[ $PGUSER == "" ]]; then
+    error "PGUSER is required for database migrations to run but found missing, aborting..."
+    exit 2
+  elif [[ $PGDATABASE == "" ]]; then
+    error "PGDATABASE is required for database migrations to run but found missing, aborting..."
+    exit 2
+  elif [[ $PGPASSWORD == "" ]]; then
+    warn "PGPASSWORD is missing, proceed at your own risk!"
+    if ! psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE < /vault/sql-src/manual/init-db.sql; then
+      error "Database migrations has failed, aborting" && exit 2
+    else
+      success "Database migrations successfully ran"
+    fi
+  else
+    if ! PGPASSWORD=$PGPASSWORD psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE < /vault/sql-src/manual/init-db.sql; then
+      error "Database migrations has failed, aborting" && exit 2
+    else
+      success "Database migrations successfully ran"
+    fi
   fi
 }
 
 startVaultServer() {
   if [[ $1 == "production" ]]; then
-      extractEnvVars
+    # Extract env vars and do checks here
+    extractEnvVars
 
-      echoStageName "Generating configuration"
-      envsubst < /vault/template.hcl > /vault/config/main.hcl
+    # Run database migrations
+    runDBMigrations
 
-      echoStageName "Starting Vault server"
-      vault server -config="$VAULT_CONFIG_DIR"
+    echoStageName "Generating configuration"
+    envsubst < /vault/template.hcl > /vault/config/main.hcl
+
+    echoStageName "Starting Vault server in production mode in 5 seconds"
+    sleep 5
+    set -- vault server -config="$VAULT_CONFIG_DIR"
+  elif [[ $1 == "development" ]]; then
+    warn "You're running Vault server in development mode, whoch the docs don't recommend to do in production and only for testing purposes only. Proceed at your own risk!"
+
+    echoStageName "Starting Vault server in development mode in 5 seconds"
+    sleep 5
+    set -- vault server \
+        -dev \
+        -dev-root-token-id="$VAULT_DEV_ROOT_TOKEN_ID" \
+        -dev-listen-address="${VAULT_DEV_LISTEN_ADDRESS:-"0.0.0.0:3000"}" \
+        "$@"
   fi
 }
 
@@ -148,8 +196,12 @@ if [ "${1:0:1}" = '-' ]; then
     set -- vault "$@"
 fi
 
-if [[ "$1" == "prod-server" ]]; then
+if [[ "$1" == "prod" ]] || [[ "$1" == "server" ]] || [[ $1 == "production" ]]; then
+  shift
   startVaultServer production
+elif [[ $1 == "dev" ]] || [[ $1 == "development" ]];then
+  shift
+  startVaultServer development
 fi
 
 exec "$@"
